# Generated by Django 3.0.6 on 2020-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_comment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auth_user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
